version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: romashka-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: Madrid2012
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - romashka_net

  brt:
    build: ./BRT
    container_name: brt-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - romashka_net

  hrs:
    build: ./HRS
    container_name: hrs-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - romashka_net

  crm:
    build: ./CRM
    container_name: crm-service
    ports:
      - "8084:8080"
    depends_on:
      - brt
    networks:
      - romashka_net

  cdr-generator:
    build: ./CDRGenerator
    container_name: CDRGenerator-service
    ports:
      - "8083:8080"
    depends_on:
      - brt
    networks:
      - romashka_net

networks:
  romashka_net:
