-- liquibase formatted sql
-- changeset anger:001-create-romashka-subscribers
CREATE TABLE IF NOT EXISTS public.romashka_subscribers (
    romashka_subscriber_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance NUMERIC(38,2) NOT NULL,
    full_name VARCHAR(255),
    last_sync TIMESTAMP NOT NULL,
    registration_date TIMESTAMP NOT NULL,
    tariff_id INTEGER NOT NULL,
    msisdn VARCHAR(12) NOT NULL,
    included_minutes INTEGER DEFAULT 0,
    last_payment_date TIMESTAMP
);

-- changeset anger:002-create-romashka-calls-info
CREATE TABLE IF NOT EXISTS public.romashka_calls_info (
    romashka_call_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_msisdn VARCHAR(12) NOT NULL,
    partner_msisdn VARCHAR(12) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    call_type VARCHAR(2) NOT NULL
);

-- changeset anger:003-insert-test-subscribers
INSERT INTO romashka_subscribers
(balance, full_name, last_sync, registration_date, tariff_id, msisdn, included_minutes, last_payment_date)
VALUES
  (100.00, 'Test User 1', '2024-12-01T00:00:00', '2023-11-12T13:00:00', 1, '+79111234567', 0, '2023-11-12T13:00:00'),
  (120.00, 'Test User 2', '2024-12-01T00:00:00', '2023-10-15T09:50:20', 1, '+79111234568', 0, '2023-10-15T09:50:20'),
  (90.00,  'Test User 3', '2024-12-01T00:00:00', '2023-06-07T12:30:00', 2, '+79111234569', 50, '2023-06-07T12:30:00'),
  (80.00,  'Test User 4', '2024-12-01T00:00:00', '2023-05-04T10:40:00', 2, '+79111234570', 50, '2023-05-04T10:40:00'),
  (75.00,  'Test User 5', '2024-12-01T00:00:00', '2023-03-02T12:00:00', 3, '+79111234571', 50, '2023-03-02T12:00:00'),
  (150.00, 'Test User 6', '2024-12-01T00:00:00', '2023-09-16T10:23:10', 3, '+79111234572', 50, '2023-09-16T10:23:10'),
  (110.00, 'Test User 7', '2024-12-01T00:00:00', '2023-04-05T22:12:14', 1, '+79111234573', 0, '2023-04-05T22:12:14'),
  (60.00,  'Test User 8', '2024-12-01T00:00:00', '2023-03-02T23:12:22', 2, '+79111234574', 50, '2023-03-02T23:12:22'),
  (95.00,  'Test User 9', '2024-12-01T00:00:00', '2023-08-15T03:55:54', 2, '+79111234575', 50, '2023-08-15T03:55:54'),
  (130.00, 'Test User 10','2024-12-01T00:00:00', '2023-10-01T01:05:06', 3, '+79111234576', 50, '2023-10-01T01:05:06');
