-- liquibase formatted sql
-- changeset anger:001-create-romashka-subscribers
CREATE TABLE IF NOT EXISTS public.romashka_subscribers (
    romashka_subscriber_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance NUMERIC(38,2) NOT NULL,
    full_name VARCHAR(255),
    last_sync TIMESTAMP NOT NULL,
    registration_date TIMESTAMP NOT NULL,
    tariff_id INTEGER NOT NULL,
    msisdn VARCHAR(12) NOT NULL
);

-- changeset anger:002-create-romashka-calls-info
CREATE TABLE IF NOT EXISTS public.romashka_calls_info (
    romashka_call_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caller VARCHAR(12) NOT NULL,
    receiver VARCHAR(12) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    call_type VARCHAR(2) NOT NULL
);